services:
  image-understanding:
    build:
      context: ./image-understanding
      dockerfile: Dockerfile
    container_name: image-understanding
    ports:
      - "${PORT:-5173}:80"
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}

  video-understanding:
    build:
      context: ./video-understanding
      dockerfile: Dockerfile
    container_name: video-understanding
    ports:
      - "${PORT:-9003}:80"
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}