services:
  spatial-understanding-front:
    build:
      context: ./spatial-understanding-front
      dockerfile: Dockerfile
    container_name: spatial-understanding-frontend
    ports:
      - "${PORT:-5173}:80"