services:
  image-understanding:
    build:
      context: ./image-understanding
      dockerfile: Dockerfile
    container_name: image-understanding
    ports:
      - "${PORT:-5173}:80"
    volumes:
      - ./credentials:/app/credentials:ro
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/credentials/claude-code-sa-key.json
      - PROJECT_ID=${PROJECT_ID}

  video-understanding:
    build:
      context: ./video-understanding
      dockerfile: Dockerfile
    container_name: video-understanding
    ports:
      - "${PORT:-9003}:80"
    volumes:
      - ./credentials:/app/credentials:ro
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/credentials/claude-code-sa-key.json
      - PROJECT_ID=${PROJECT_ID}