services:
  image-understanding:
    build:
      context: ./image-understanding
      dockerfile: Dockerfile
    container_name: image-understanding
    ports:
      - "${IMAGE_PORT:-5173}:8080"
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - PORT=8080

  video-understanding:
    build:
      context: ./video-understanding
      dockerfile: Dockerfile
    container_name: video-understanding
    ports:
      - "${VIDEO_PORT:-9003}:8080"
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - PORT=8080