services:
  spatial-understanding-front:
    build:
      context: ./spatial-understanding-front
      dockerfile: Dockerfile
    container_name: spatial-understanding-front
    ports:
      - "${PORT:-5173}:80"
    volumes:
      - ./gcp-service-account.json:/app/gcp-service-account.json:ro
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/gcp-service-account.json
      - GOOGLE_CLOUD_PROJECT=${GOOGLE_CLOUD_PROJECT}