name: Docker Build Test

on:
  pull_request:
    branches: [ main ]

jobs:
  docker-build-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Test Docker build
      uses: docker/build-push-action@v5
      with:
        context: .
        push: false
        tags: test:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Build test summary
      run: |
        echo "### ✅ Docker Build Test Passed" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "Docker image builds successfully and is ready for production." >> $GITHUB_STEP_SUMMARY

