apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-understanding
  namespace: spatial-understanding
  labels:
    app: image-understanding
spec:
  replicas: 2
  selector:
    matchLabels:
      app: image-understanding
  template:
    metadata:
      labels:
        app: image-understanding
    spec:
      serviceAccountName: workload-identity-sa
      containers:
      - name: image-understanding
        image: gcr.io/PROJECT_ID/image-understanding:v1.0.0
        ports:
        - containerPort: 8080
        env:
        - name: PROJECT_ID
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: PROJECT_ID
        - name: GEMINI_API_KEY
          valueFrom:
            secretKeyRef:
              name: gemini-credentials
              key: GEMINI_API_KEY
        - name: PORT
          value: "8080"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: image-understanding-svc
  namespace: spatial-understanding
spec:
  selector:
    app: image-understanding
  ports:
  - port: 80
    targetPort: 8080
  type: ClusterIP