apiVersion: v1
kind: Secret
metadata:
  name: gemini-credentials
  namespace: ${K8S_NAMESPACE}
  labels:
    app.kubernetes.io/managed-by: cloud-build
type: Opaque
stringData:
  GEMINI_API_KEY: "${GEMINI_API_KEY}"  # This will be set by Cloud Build