apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: ${K8S_NAMESPACE}
  labels:
    app.kubernetes.io/managed-by: cloud-build
data:
  PROJECT_ID: "${PROJECT_ID}"
  NODE_ENV: "production"
  CONTAINER_REGISTRY: "${CONTAINER_REGISTRY}"