# Conditional Service Account based on authentication method
# Only needed for Workload Identity (_USE_SA_KEY=false)
apiVersion: v1
kind: ServiceAccount
metadata:
  name: workload-identity-sa
  namespace: ${K8S_NAMESPACE}
  annotations:
    # Only add this annotation if using Workload Identity
    iam.gke.io/gcp-service-account: ${SERVICE_ACCOUNT_EMAIL}
  labels:
    app.kubernetes.io/managed-by: cloud-build
# Note: This file will be applied regardless, but the annotation only matters for Workload Identity