apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: media-understanding-ingress
  namespace: ${K8S_NAMESPACE}
  labels:
    app.kubernetes.io/managed-by: cloud-build
  annotations:
    # Use modern ingress class specification
    kubernetes.io/ingress.class: "gce"
    # Static IP binding - this is the critical annotation
    kubernetes.io/ingress.global-static-ip-name: "${STATIC_IP_NAME}"
    # Enable NEG for better load balancing
    cloud.google.com/neg: '{"ingress": true}'
    # SSL certificate (optional but recommended)
    networking.gke.io/managed-certificates: "media-understanding-ssl"
spec:
  # Add TLS configuration to use the managed certificate
  tls:
  - hosts:
    - ${INGRESS_HOSTNAME}
    secretName: media-understanding-ssl
  rules:
  - host: ${INGRESS_HOSTNAME}
    http:
      paths:
      # Order matters - more specific paths first
      - path: /image
        pathType: Prefix
        backend:
          service:
            name: image-understanding-svc
            port:
              number: 80
      - path: /video
        pathType: Prefix
        backend:
          service:
            name: video-understanding-svc
            port:
              number: 80
      # Default root path
      - path: /
        pathType: Prefix
        backend:
          service:
            name: image-understanding-svc
            port:
              number: 80
---
# Managed SSL certificate for HTTPS
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: media-understanding-ssl
  namespace: ${K8S_NAMESPACE}
spec:
  domains:
  - ${INGRESS_HOSTNAME}
---
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: media-understanding-backendconfig
  namespace: ${K8S_NAMESPACE}
spec:
  # Health check configuration for Autopilot
  healthCheck:
    checkIntervalSec: 15
    timeoutSec: 10
    healthyThreshold: 1
    unhealthyThreshold: 3
    type: HTTP
    requestPath: /healthz
    port: 8080
  # Session affinity for better performance
  sessionAffinity:
    affinityType: "CLIENT_IP"
    affinityCookieTtlSec: 3600
  # Connection draining
  connectionDraining:
    drainingTimeoutSec: 60